### ISSUE TITLE
Liens inopérants

### ISSUE THREAD

**Issue by isabvllv** [dcycle/starterkit-mediawiki#2]
Pages nouvellement inaccessibles (mettent trop de temps à répondre)  : http://167.71.107.185:8080/ , 167.71.107.185:8080/index.php/ACCUEIL#Fa.C3.A7ons_de_naviguer , http://167.71.107.185:8080/index.php/My_First_Page  (ERR_CONNECTION_TIMED_OUT)

**Comment by alberto56** [comment]
J'ai installé ça sur un nouveau serveur au http://67.205.187.95:8080

Utilisez le même compte pour vous connecter.

Vos anciennes données seront perdues; J'ai installé un système de backup, vos données ne seront plus perdues dorénavant.

**Comment by alberto56** [comment]
It is now possible to install extensions, documented in the README.md file.

See https://github.com/LeHubca/lehub-mediawiki/issues/2 for le hub wiki; closing
