### ISSUE TITLE
Insérer le logo du HUB en modifiant le fichier LocalSetting.php 

### ISSUE THREAD

**Issue by isabvllv** [dcycle/starterkit-mediawiki#3]
https://www.mediawiki.org/wiki/Manual:FAQ#How_do_I_change_the_logo?

**Comment by alberto56** [comment]
Il est maintenant possible d'insérer votre logo

SVP insérer votre logo au http://67.205.187.95:8080/index.php/Special:Upload

et mettez le lien (URL) vers le logo ici

**Comment by isabvllv** [comment]
Salut Albert! 
L'image a été insérée au lien fourni. 
Lien de l'image : https://www.lehub.ca/img/logo.png

**Comment by alberto56** [comment]
Ceci fonctionne pour le hub au https://github.com/LeHubca/lehub-mediawiki/issues/1

**Comment by alberto56** [comment]
Closing
